name: PR Build

on:
  push:
    branches:
      - main
  pull_request: {}
  workflow_dispatch: {}

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-logic:
    runs-on:
      labels: macOS
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1
          lfs: 'true'
      - uses: ./.github/actions/setup-env
        with:
          gradle_encryption_key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
      - name: Check build-logic
        run: ./gradlew :build-logic:check

  build-server:
    runs-on: [self-hosted, linux]
    needs: build-logic
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1
          lfs: 'true'
      - uses: ./.github/actions/setup-env
        with:
          gradle_encryption_key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
      - name: Gradle assemble
        run: ./gradlew :server:app:assemble
  build-cli:
    runs-on: self-hosted
    needs: build-server
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1
          lfs: 'true'
      - uses: ./.github/actions/setup-env
        with:
          gradle_encryption_key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
      - name: Gradle assemble
        run: ./gradlew :cli:app:assemble

  build-client:
    runs-on:
      labels: macOS
    needs: build-logic
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1
          lfs: 'true'
      - uses: ./.github/actions/setup-env
        with:
          gradle_encryption_key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
      - name: Gradle assemble
        run: ./gradlew :client:composeApp:assemble
